# Generated by Django 2.1.7 on 2019-05-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=10, verbose_name='고용주')),
                ('employee', models.CharField(max_length=10, verbose_name='근로자')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('workday', models.CharField(max_length=6)),
                ('holiday', models.CharField(max_length=6)),
                ('work_place', models.CharField(max_length=30, verbose_name='근무 장소')),
                ('work_content', models.CharField(max_length=50, verbose_name='업무내용')),
                ('salary', models.IntegerField(default=0)),
                ('year_holiday', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='mmim',
            name='adr1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mmim',
            name='jm',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mmim',
            name='name',
            field=models.CharField(max_length=10, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='mmim',
            name='pn',
            field=models.CharField(max_length=20),
        ),
    ]
