# Generated by Django 2.1.7 on 2019-05-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20190529_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
