# Generated by Django 2.2 on 2019-05-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_auto_20190530_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='elections.MMIM', verbose_name='근로자'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='elections.MMIM', verbose_name='고용주'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(verbose_name='근로 종료 기간'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='근로 마감 시간'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='holiday',
            field=models.CharField(max_length=6, verbose_name='휴일'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='월급'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(verbose_name='근로 시작 기간'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='근로 시작 시간'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='workday',
            field=models.CharField(max_length=6, verbose_name='근무일'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='year_holiday',
            field=models.IntegerField(default=0, verbose_name='연차 유급 휴가'),
        ),
    ]
